FROM registry.cn-shenzhen.aliyuncs.com/jzdev/tinibase:1.0.0

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 安装node,保证环境中有JS环境
RUN wget https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.xz
RUN xz -d node-v10.15.3-linux-x64.tar.xz
RUN tar -xvf node-v10.15.3-linux-x64.tar

# 添加软链接
RUN ln -s /node-v10.15.3-linux-x64/bin/node /usr/local/bin/node
RUN ln -s /node-v10.15.3-linux-x64/bin/npm /usr/local/bin/npm

RUN mkdir /hkland_flow

WORKDIR /hkland_flow

ADD . /hkland_flow

WORKDIR /hkland_flow

RUN pip install -r requirements.txt -i https://pypi.douban.com/simple

ENTRYPOINT ["python", "jqka10_flow.py"]